### ISSUE TITLE
Error handling response: TypeError: Cannot read properties of null (reading 'appendChild')

### ISSUE THREAD

**Issue by AndreLion** [steampunck/swoosh-storage-specialist#7]
```
Error handling response: TypeError: Cannot read properties of null (reading 'appendChild')
    at W (chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js:1:8723)
    at F (chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js:1:11194)
    at chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js:1:5401
```

**Comment by AndreLion** [comment]
请问在任何页面都能重现这个问题吗？比如 Playground ： https://steampunck.github.io/swoosh-storage-specialist/playground.html

**Comment by AndreLion** [comment]
貌似 Extension ID `ncennffkjdiamlpmcbajkmaiiiddgioo` 是另一个插件 “迅雷下载支持”，可能是这两个插件有冲突 🤔

**Comment by AndreLion** [comment]
Might be an obsolete issue since a new version 3.0.0 was launched.
Closing this issue. Will re-open it if it still exists.
Thanks.
